/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cameronjharvey;

/**
 *
 * @author Cameron
 */

public class MainFrame extends java.awt.Frame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
public void UpdateLog(String text)
{
    txtLog.appendText(text + "\n");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLog = new java.awt.TextArea();
        btnEnrolment = new javax.swing.JButton();
        btnLearnings = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setResizable(false);
        setTitle("TraQCEr Data Injector");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        txtLog.setBackground(new java.awt.Color(0, 0, 0));
        txtLog.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLog.setEditable(false);
        txtLog.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLog.setForeground(java.awt.Color.orange);

        btnEnrolment.setText("Import Enrolment data");
        btnEnrolment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnrolmentMouseClicked(evt);
            }
        });

        btnLearnings.setText("Import Learnings data");
        btnLearnings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLearningsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnrolment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLearnings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnrolment)
                    .addComponent(btnLearnings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLog, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );

        txtLog.getAccessibleContext().setAccessibleName("txtLog");
        txtLog.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnLearningsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLearningsMouseClicked
        // Run Learnings Import
        TraQCErDataInjector.ImportLearningsData();
    }//GEN-LAST:event_btnLearningsMouseClicked

    private void btnEnrolmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrolmentMouseClicked
        // Run Enrolment Import
        TraQCErDataInjector.ImportEnrolmentData();
    }//GEN-LAST:event_btnEnrolmentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrolment;
    private javax.swing.JButton btnLearnings;
    private java.awt.TextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
